name: Push latest
on:
  push:
    branches:
      - develop
jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
    - name: Copia repositorio
      uses: actions/checkout@v2
    - name: Construye imagen
      run: docker build --tag islasgeci/dummy_transformations:latest --tag islasgeci/dummy_transformations:${GITHUB_SHA:0:4} .
    - name: Verifica el formato
      run: docker run islasgeci/dummy_transformations:latest make check
    - name: Corre pruebas y evalúa cobertura
      run: docker run islasgeci/dummy_transformations:latest make coverage
    - name: Evalúa resistencia a mutaciones
      run: docker run islasgeci/dummy_transformations:latest make mutants
